vim.keymap.set("n", "<leader>L", "<Cmd>Lazy<CR>", { desc = 'Lazy' })

vim.keymap.set("n", "<leader>q", "<Cmd>q<CR>", { desc = "Quit All" })

vim.keymap.set("n", "<leader>bb", "<Cmd>b#<CR>", { desc = "Back" })
vim.keymap.set("n", "<leader>bd", "<Cmd>bdelete<CR>", { desc = "Delete" })
vim.keymap.set("n", "<leader>bn", "<Cmd>enew<CR>", { desc = "New" })
vim.keymap.set('n', '<leader>br', '<Cmd>e!<CR>', { desc = "Reload" })
vim.keymap.set('n', '<leader>bw', '<Cmd>w<CR>', { desc = "Save" })
vim.keymap.set('n', '<leader>s', '<Cmd>w<CR>', { desc = "Save" })

vim.keymap.set("n", "<leader>wd", "<Cmd>close<CR>", { desc = "Delete (Window)" })
vim.keymap.set("n", "<leader>wh", "<Cmd>split<CR>", { desc = "Split (Horizontal)" })
vim.keymap.set("n", "<leader>wn", "<Cmd>vnew<Bar>wincmd L<CR>", { desc = "New (Vertical)" })
vim.keymap.set("n", "<leader>wH", "<C-W>H", { desc = "Move Left" })
vim.keymap.set("n", "<leader>wJ", "<C-W>J", { desc = "Move Down" })
vim.keymap.set("n", "<leader>wK", "<C-W>K", { desc = "Move Up" })
vim.keymap.set("n", "<leader>wL", "<C-W>L", { desc = "Move Right" })
vim.keymap.set("n", "<leader>wv", "<Cmd>vsplit<CR>", { desc = "Split (Vertical)" })

vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move Left" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move Down" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move Up" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move Right" })
vim.keymap.set("n", "<C-Up>", "<Cmd>resize +2<CR>", { desc = "Increase Height" })
vim.keymap.set("n", "<C-Down>", "<Cmd>resize -2<CR>", { desc = "Decrease Height" })
vim.keymap.set("n", "<C-Left>", "<Cmd>vertical resize -2<CR>", { desc = "Decrease Width" })
vim.keymap.set("n", "<C-Right>", "<Cmd>vertical resize +2<CR>", { desc = "Increase Width" })

vim.keymap.set("n", "<M-j>", "<Cmd>execute 'move .+' . v:count1<CR>", { desc = "Move Lines Down" })
vim.keymap.set("n", "<M-k>", "<Cmd>execute 'move .-' . (v:count1 + 1)<CR>", { desc = "Move Lines Up" })
vim.keymap.set("v", "<M-j>", ":m '>+1<CR>gv=gv", { desc = "Move Lines Down", silent = true })
vim.keymap.set("v", "<M-k>", ":m '<-2<CR>gv=gv", { desc = "Move Lines Up", silent = true })

vim.keymap.set({ 'n', 'v' }, 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true })
vim.keymap.set({ 'n', 'v' }, 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true })
vim.keymap.set("n", "<M-h>", "10zh", { desc = "Scroll Left" })
vim.keymap.set("n", "<M-l>", "10zl", { desc = "Scroll Right" })
vim.keymap.set("n", "<M-H>", "zH", { desc = "Scroll Left!" })
vim.keymap.set("n", "<M-L>", "zL", { desc = "Scroll Right!" })
vim.keymap.set("n", "<Esc>", "<Cmd>nohlsearch<CR>", { desc = "Clear Search Highlight" })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left and stay in visual mode" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right and stay in visual mode" })

vim.keymap.set({"n", "v"}, "<leader>.", vim.lsp.buf.code_action, { desc = "Action" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Action" })
vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename, { desc = "Rename Symbol" })
vim.keymap.set("n", "<leader>cl", "<Cmd>LspInfo<CR>", { desc = "LSP Info" })
